export const NEXT_PUBLIC_STRING_METADATA_TITLE = process.env.NEXT_PUBLIC_STRING_METADATA_TITLE;
export const NEXT_PUBLIC_STRING_METADATA_DESCRIPTION =
  process.env.NEXT_PUBLIC_STRING_METADATA_DESCRIPTION;

export const NEXT_PUBLIC_STRING_GIT_PROVIDER_NAME =
  process.env.NEXT_PUBLIC_STRING_GIT_PROVIDER_NAME;
export const NEXT_PUBLIC_STRING_GIT_PROVIDER_LINK =
  process.env.NEXT_PUBLIC_STRING_GIT_PROVIDER_LINK;

export const NEXT_PUBLIC_STRING_WEBSITE_NAME = process.env.NEXT_PUBLIC_STRING_WEBSITE_NAME;
export const NEXT_PUBLIC_STRING_WEBSITE_LINK = process.env.NEXT_PUBLIC_STRING_WEBSITE_LINK;

export const STRIPE_SECRET_KEY = process.env.STRIPE_SECRET_KEY!;
export const NEXT_PUBLIC_STRIPE_PRICE_ID_DONATE = process.env.NEXT_PUBLIC_STRIPE_PRICE_ID_DONATE!;
export const NEXT_PUBLIC_STRIPE_PRICE_ID_SPONSOR_BRONZE_M =
  process.env.NEXT_PUBLIC_STRIPE_PRICE_ID_SPONSOR_BRONZE_M!;
export const NEXT_PUBLIC_STRIPE_PRICE_ID_SPONSOR_BRONZE_Y =
  process.env.NEXT_PUBLIC_STRIPE_PRICE_ID_SPONSOR_BRONZE_Y!;
export const NEXT_PUBLIC_STRIPE_PRICE_ID_SPONSOR_SILVER_M =
  process.env.NEXT_PUBLIC_STRIPE_PRICE_ID_SPONSOR_SILVER_M!;
export const NEXT_PUBLIC_STRIPE_PRICE_ID_SPONSOR_SILVER_Y =
  process.env.NEXT_PUBLIC_STRIPE_PRICE_ID_SPONSOR_SILVER_Y!;
export const NEXT_PUBLIC_STRIPE_PRICE_ID_SPONSOR_GOLD_M =
  process.env.NEXT_PUBLIC_STRIPE_PRICE_ID_SPONSOR_GOLD_M!;
export const NEXT_PUBLIC_STRIPE_PRICE_ID_SPONSOR_GOLD_Y =
  process.env.NEXT_PUBLIC_STRIPE_PRICE_ID_SPONSOR_GOLD_Y!;

export const NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY!;
if (!NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY) {
  throw new Error('process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY is undefined');
}

export const NEXT_PUBLIC_ADDRESS_ETH = process.env.NEXT_PUBLIC_ADDRESS_ETH;
export const NEXT_PUBLIC_STRING_CRYPTO_DESCRIPTION =
  process.env.NEXT_PUBLIC_STRING_CRYPTO_DESCRIPTION;
export const NEXT_PUBLIC_ADDRESS_BTC = process.env.NEXT_PUBLIC_ADDRESS_BTC;
export const NEXT_PUBLIC_ADDRESS_BTC_DESCRIPTION = process.env.NEXT_PUBLIC_ADDRESS_BTC_DESCRIPTION;
export const NEXT_PUBLIC_ADDRESS_SOL = process.env.NEXT_PUBLIC_ADDRESS_SOL;
export const NEXT_PUBLIC_ADDRESS_SOL_DESCRIPTION = process.env.NEXT_PUBLIC_ADDRESS_SOL_DESCRIPTION;

export const NEXT_PUBLIC_ENABLE_SPONSORS = process.env.NEXT_PUBLIC_ENABLE_SPONSORS;
export const NEXT_PUBLIC_ENABLE_ONE_TIME_CARD_DONATION =
  process.env.NEXT_PUBLIC_ENABLE_ONE_TIME_CARD_DONATION;

export const NEXT_PUBLIC_STRING_CARD_DESCRIPTION = process.env.NEXT_PUBLIC_STRING_CARD_DESCRIPTION;
